version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "package-lock.json" }}
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-{{ checksum "package-lock.json" }}
      - run: npm test -- --coverage
      - run:
          name: Coverage Report
          command: bash <(curl -s https://codecov.io/bash)
